spring.application.name=apifilme

spring.datasource.url=jdbc:h2:mem:filmedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Testes
#
#Caso de teste
#?	ID: CT-001
#?	Objetivo: criar filme com sucesso
#?	Pré-condição: gênero existente
#?	Entrada: JSON válido
#?	Passos:
#1.	fazer POST /filmes
#2.	enviar body
#?	Resultado esperado:
#?	status 201
#?	campo id preenchido
#?	título correto


